name: Build plugin

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build jar (skip tests)
        run: ./gradlew --no-daemon --stacktrace jar -x test

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MCreatorMCP-artifact
          path: build/libs/MCreatorMCP.zip
          if-no-files-found: error
          retention-days: 7


